import path from 'path';
import { chromium } from 'playwright';
const browser = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required'] });
const page = await (await browser.newContext({ viewport: { width: 393, height: 852 }, deviceScaleFactor: 3, hasTouch: true, isMobile: true })).newPage();
page.on('pageerror', e => console.log('[pageerror]', e.message));
await page.goto('file://' + path.resolve('out/photon64.html') + '?insets=59,0,34,0');
await page.waitForTimeout(500);
await page.screenshot({ path: process.argv[3] + '_home.png', clip: { x: 193, y: 0, width: 200, height: 90 } });
await page.setInputFiles('#file', process.argv[2]); await page.waitForTimeout(3000);
await page.tap('#b-menu'); await page.waitForTimeout(400);
await page.screenshot({ path: process.argv[3] + '_menu.png' });
await page.tap('#m-set');
const snap = () => page.evaluate(() => { const s = window.__photon.settings, q = id => document.getElementById(id); return { s: JSON.stringify({ ...s, keys: s.keys.A }), aspect: q('s-aspect').value, seg: [...q('s-aspect')._seg.children].findIndex(b => b.classList.contains('on')), vif: q('s-vif').checked, vol: q('s-vol').value, tsize: q('s-tsize').value, zr: q('s-zr').checked, cpi: q('s-cpi').value, bind: q('binds').children[4].lastChild.textContent, dpadShown: !!document.querySelector('#dpad').offsetParent || !document.querySelector('#dpad').hidden }; });
const d0 = await snap();
await page.evaluate(() => { const q = id => document.getElementById(id), ch = (id, v) => { const e = q(id); if (e.type === 'checkbox') e.checked = v; else e.value = v; e.dispatchEvent(new Event(e.type === 'range' ? 'input' : 'change')); };
  ch('s-aspect', '1'); ch('s-vif', false); ch('s-vol', '20'); ch('s-tsize', '80'); ch('s-zr', true); ch('s-cpi', '8'); ch('s-dpad', false); ch('s-hud', true); window.__photon.settings.keys.A = 'KeyP'; window.__photon.settings.mute = true; });
const d1 = await snap();
await page.tap('#tabs [data-tab=data]'); await page.waitForTimeout(200);
await page.tap('#s-defaults'); await page.waitForTimeout(200);
await page.screenshot({ path: process.argv[3] + '_data.png' });
const mid = await snap();
await page.tap('#s-defaults'); await page.waitForTimeout(400);
const d2 = await snap();
console.log('changed    ', d1.s !== d0.s, d1.seg, d1.vol);
console.log('first tap only arms', mid.s === d1.s, await page.evaluate(() => 1));
console.log('restored   ', d2.s === d0.s && d2.seg === d0.seg && d2.vif === d0.vif && d2.vol === d0.vol && d2.tsize === d0.tsize && d2.zr === d0.zr && d2.cpi === d0.cpi && d2.bind === d0.bind, JSON.stringify(d2));
console.log('hud hidden again', await page.evaluate(() => document.getElementById('hud').hidden), 'toast:', await page.evaluate(() => document.getElementById('toast').textContent), 'game still loaded:', await page.evaluate(() => !!window.__photon.rom));
await page.reload(); await page.waitForTimeout(500);
console.log('after reload', (await page.evaluate(() => JSON.stringify({ ...window.__photon.settings, keys: window.__photon.settings.keys.A }))) === d0.s, 'library kept:', await page.evaluate(async () => (await window.__photon.libList()).length));
await browser.close();
